#!/bin/bash
files=$(ls -1 | grep \.cuberdg)
files=($files)
#echo $files
#files=($files)
#echo $files
echo > all.vmd
echo "cd [file dirname [info script]]" >> all.vmd
for a in "${files[@]}"; do
	echo $a
	#echo $i
	name="${a%.*}"
	echo $name
	printf  "set next [mol new \"" > $name".vmd"
	printf  "%s" $a  >> $name".vmd"
	echo "\" type cube first 0 last -1 step 1 filebonds off autobonds off waitfor all ]"  >> $name".vmd"
	#echo "axes location Off" >> $name".vmd"
        #echo "color Display Background white" >> $name".vmd"	
	echo "mol addfile "$name".cuberhosign type cube first 0 last -1 step 1 filebonds off autobonds off waitfor all" >>$name".vmd"
	echo "mol delrep 0 top" >> $name".vmd"


	echo "mol representation Isosurface "$1" 0 0 0 1 1" >> $name".vmd"
	echo "mol color Volume 1" >> $name".vmd"
	#echo "mol selection {all}" >> $name".vmd"
	echo "mol material Opaque" >> $name".vmd"
	echo "mol addrep top" >> $name".vmd"
	echo >> $name".vmd"
	#echo "mol selupdate 0 top 0" >> $name".vmd"
	#echo "mol colupdate 0 top 0" >> $name".vmd"
	#echo "mol scaleminmax top 0 $2 $3" >> $name".vmd"
	#echo "mol smoothrep top 0 0" >> $name".vmd"
	#echo "mol drawframes top 0 {now}" >> $name".vmd"
	echo "color scale method BGR" >> $name".vmd"
	
	echo "source" $name".vmd" >> all.vmd
	echo >> all.vmd
done
